// Code generated by protoc-gen-go. DO NOT EDIT.
// source: learning.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Learning struct {
	// Id for the neural network used.
	IdNN                 int32     `protobuf:"varint,1,opt,name=idNN,proto3" json:"idNN,omitempty"`
	Outputs              []float64 `protobuf:"fixed64,2,rep,packed,name=outputs,proto3" json:"outputs,omitempty"`
	Weights              []float64 `protobuf:"fixed64,3,rep,packed,name=weights,proto3" json:"weights,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Learning) Reset()         { *m = Learning{} }
func (m *Learning) String() string { return proto.CompactTextString(m) }
func (*Learning) ProtoMessage()    {}
func (*Learning) Descriptor() ([]byte, []int) {
	return fileDescriptor_learning_a164bf0ac33df2b2, []int{0}
}
func (m *Learning) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Learning.Unmarshal(m, b)
}
func (m *Learning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Learning.Marshal(b, m, deterministic)
}
func (dst *Learning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Learning.Merge(dst, src)
}
func (m *Learning) XXX_Size() int {
	return xxx_messageInfo_Learning.Size(m)
}
func (m *Learning) XXX_DiscardUnknown() {
	xxx_messageInfo_Learning.DiscardUnknown(m)
}

var xxx_messageInfo_Learning proto.InternalMessageInfo

func (m *Learning) GetIdNN() int32 {
	if m != nil {
		return m.IdNN
	}
	return 0
}

func (m *Learning) GetOutputs() []float64 {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *Learning) GetWeights() []float64 {
	if m != nil {
		return m.Weights
	}
	return nil
}

func init() {
	proto.RegisterType((*Learning)(nil), "pb.Learning")
}

func init() { proto.RegisterFile("learning.proto", fileDescriptor_learning_a164bf0ac33df2b2) }

var fileDescriptor_learning_a164bf0ac33df2b2 = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x49, 0x4d, 0x2c,
	0xca, 0xcb, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x0a,
	0xe2, 0xe2, 0xf0, 0x81, 0x8a, 0x0a, 0x09, 0x71, 0xb1, 0x64, 0xa6, 0xf8, 0xf9, 0x49, 0x30, 0x2a,
	0x30, 0x6a, 0xb0, 0x06, 0x81, 0xd9, 0x42, 0x12, 0x5c, 0xec, 0xf9, 0xa5, 0x25, 0x05, 0xa5, 0x25,
	0xc5, 0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0x8c, 0x41, 0x30, 0x2e, 0x48, 0xa6, 0x3c, 0x35, 0x33, 0x3d,
	0xa3, 0xa4, 0x58, 0x82, 0x19, 0x22, 0x03, 0xe5, 0x26, 0xb1, 0x81, 0x8d, 0x37, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xa0, 0xe2, 0x5d, 0x6c, 0x70, 0x00, 0x00, 0x00,
}
