// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nn.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NeuralNetwork struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Layer                []int32              `protobuf:"varint,2,rep,packed,name=layer,proto3" json:"layer,omitempty"`
	Weight               []float64            `protobuf:"fixed64,3,rep,packed,name=weight,proto3" json:"weight,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NeuralNetwork) Reset()         { *m = NeuralNetwork{} }
func (m *NeuralNetwork) String() string { return proto.CompactTextString(m) }
func (*NeuralNetwork) ProtoMessage()    {}
func (*NeuralNetwork) Descriptor() ([]byte, []int) {
	return fileDescriptor_nn_22ebc5c969e6f0cb, []int{0}
}
func (m *NeuralNetwork) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeuralNetwork.Unmarshal(m, b)
}
func (m *NeuralNetwork) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeuralNetwork.Marshal(b, m, deterministic)
}
func (dst *NeuralNetwork) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeuralNetwork.Merge(dst, src)
}
func (m *NeuralNetwork) XXX_Size() int {
	return xxx_messageInfo_NeuralNetwork.Size(m)
}
func (m *NeuralNetwork) XXX_DiscardUnknown() {
	xxx_messageInfo_NeuralNetwork.DiscardUnknown(m)
}

var xxx_messageInfo_NeuralNetwork proto.InternalMessageInfo

func (m *NeuralNetwork) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NeuralNetwork) GetLayer() []int32 {
	if m != nil {
		return m.Layer
	}
	return nil
}

func (m *NeuralNetwork) GetWeight() []float64 {
	if m != nil {
		return m.Weight
	}
	return nil
}

func (m *NeuralNetwork) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

func init() {
	proto.RegisterType((*NeuralNetwork)(nil), "pb.NeuralNetwork")
}

func init() { proto.RegisterFile("nn.proto", fileDescriptor_nn_22ebc5c969e6f0cb) }

var fileDescriptor_nn_22ebc5c969e6f0cb = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc8, 0xcb, 0xd3, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x92, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49,
	0xd5, 0x07, 0x8b, 0x24, 0x95, 0xa6, 0xe9, 0x97, 0x64, 0xe6, 0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16,
	0x40, 0x14, 0x29, 0xf5, 0x30, 0x72, 0xf1, 0xfa, 0xa5, 0x96, 0x16, 0x25, 0xe6, 0xf8, 0xa5, 0x96,
	0x94, 0xe7, 0x17, 0x65, 0x0b, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0,
	0x06, 0x31, 0x65, 0xa6, 0x08, 0x89, 0x70, 0xb1, 0xe6, 0x24, 0x56, 0xa6, 0x16, 0x49, 0x30, 0x29,
	0x30, 0x6b, 0xb0, 0x06, 0x41, 0x38, 0x42, 0x62, 0x5c, 0x6c, 0xe5, 0xa9, 0x99, 0xe9, 0x19, 0x25,
	0x12, 0xcc, 0x0a, 0xcc, 0x1a, 0x8c, 0x41, 0x50, 0x9e, 0x90, 0x2d, 0x17, 0x4f, 0x4e, 0x62, 0x71,
	0x49, 0x7c, 0x69, 0x41, 0x4a, 0x62, 0x49, 0x6a, 0x8a, 0x04, 0x8b, 0x02, 0xa3, 0x06, 0xb7, 0x91,
	0x94, 0x1e, 0xc4, 0x1d, 0x7a, 0x30, 0x77, 0xe8, 0x85, 0xc0, 0xdc, 0x11, 0xc4, 0x0d, 0x52, 0x1f,
	0x0a, 0x51, 0x9e, 0xc4, 0x06, 0x56, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x72, 0x3f, 0x7a,
	0x91, 0xc6, 0x00, 0x00, 0x00,
}
